################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
home = "Home"

################################### French language #####################################
[pt]
languageName = "Pt"
languageCode = "pt-pt"
contentDir = "content/portuguese"
weight = 2
[pt.params]
home = "Home"





