
################### Portuguese Navigation ########################
[[main]]
name = "sobre"
url = "#about"
weight = 1

[[main]]
name = "serviço"
url = "#services"
weight = 2

[[main]]
name = "portfólio"
url = "#portfolio"
weight = 3

[[main]]
name = "equipe"
url = "#team"
weight = 4

[[main]]
name = "preços"
url = "#pricing"
weight = 5

[[main]]
name = "blog"
url = "#blog"
weight = 6

[[main]]
name = "contato"
url = "#contact"
weight = 7
